# Generated by Django 4.2.2 on 2023-07-15 10:32

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_name', models.CharField(max_length=20)),
                ('notes_text', models.TextField(default='text here...')),
                ('notes_created_on', models.DateTimeField(auto_now_add=True)),
                ('notes_last_modified', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField(blank=True, default='None', max_length=50)),
                ('notes_slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='notes_anme')),
                ('bookmark_notes', models.BooleanField(default=False)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notebook.notebook')),
            ],
        ),
    ]
