# Generated by Django 4.2.2 on 2023-07-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_diff',
            field=models.DurationField(blank=True, default=None),
        ),
    ]
