# Generated by Django 4.2.2 on 2023-07-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_time_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_diff',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
