# Generated by Django 4.2.2 on 2023-07-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank='True', upload_to='attachments/uploads')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notes')),
            ],
        ),
    ]
