# Generated by Django 4.2.2 on 2023-07-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share_notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('shared_by', models.EmailField(max_length=20)),
                ('notebook', models.CharField(max_length=20)),
            ],
        ),
    ]
